export type SectionField = {
  name: string;
  label: string;
  type: "text" | "textarea" | "url" | "file";
  placeholder?: string;
  helper?: string;
  fullWidth?: boolean;
};

export type SectionConfig = {
  key: string;
  slug: string;
  title: string;
  tagline: string;
  description: string;
  gradient: string;
  fields: SectionField[];
  sampleEntries: Record<string, string>[];
};

export const projectSections: SectionConfig[] = [
  {
    key: "logo",
    slug: "logo",
    title: "Logo Solutions",
    tagline: "Hero marks, mockups & assets",
    description:
      "Upload the hero mark, supporting mockups and give context for the brand narrative.",
    gradient: "from-purple-500/70 via-pink-500/60 to-orange-400/60",
    fields: [
      {
        name: "companyName",
        label: "Company Name",
        type: "text",
        placeholder: "Orbit CRM",
      },
      {
        name: "clientContact",
        label: "Client Contact Information",
        type: "textarea",
        placeholder: "Name, email, phone, company role",
      },
      {
        name: "projectDescription",
        label: "Project Description",
        type: "textarea",
        placeholder: "Reimagined the Orbit CRM visual identity through ...",
        fullWidth: true,
      },
      {
        name: "projectYear",
        label: "Project Year",
        type: "text",
        placeholder: "2024",
      },
      {
        name: "projectTimeline",
        label: "Project Timeline / Deadline",
        type: "textarea",
        placeholder: "Start date, milestones, completion date",
      },
      {
        name: "primaryLogo",
        label: "Hero Logo / Mark URL",
        type: "url",
        placeholder: "https://cdn.webfudge.com/orbit/hero-mark.png",
        helper: "Paste an image URL or upload in the mockup field below.",
      },
      {
        name: "logoVariations",
        label: "Logo Variations",
        type: "textarea",
        placeholder: "Horizontal, vertical, icon only, wordmark, monogram variations",
        fullWidth: true,
      },
      {
        name: "logoSizes",
        label: "Logo Size Variations",
        type: "textarea",
        placeholder: "Full size, medium, small, favicon sizes",
      },
      {
        name: "backgroundVariations",
        label: "Background Variations",
        type: "textarea",
        placeholder: "Light background, dark background, transparent, colored backgrounds",
      },
      {
        name: "colorPalette",
        label: "Color Palette",
        type: "textarea",
        placeholder: "Primary colors, secondary colors, hex codes, RGB values",
        fullWidth: true,
      },
      {
        name: "typography",
        label: "Typography Used",
        type: "textarea",
        placeholder: "Font families, weights, custom lettering details",
      },
      {
        name: "animationLogo",
        label: "Animated / Motion Logo",
        type: "url",
        placeholder: "Link to animated logo (GIF, video, Lottie)",
        helper: "If applicable, include animated logo variations",
      },
      {
        name: "fileFormats",
        label: "File Formats Delivered",
        type: "textarea",
        placeholder: "SVG, PNG (transparent), PDF, EPS, AI, JPG",
      },
      {
        name: "supportingAssets",
        label: "Supporting Assets & Mockups",
        type: "textarea",
        placeholder:
          "Car wrap mockups, carry bag system, stationery kit, packaging, merchandise, etc.",
        fullWidth: true,
      },
      {
        name: "logoUsageGuidelines",
        label: "Logo Usage Guidelines",
        type: "textarea",
        placeholder: "Minimum size, clear space, do's and don'ts, placement rules",
        fullWidth: true,
      },
      {
        name: "brandGuidelinesLink",
        label: "Brand Guidelines Link",
        type: "url",
        placeholder: "https://notion.so/brand-guidelines or PDF link",
      },
      {
        name: "inspirationMoodboard",
        label: "Inspiration / Mood Board Links",
        type: "textarea",
        placeholder: "Pinterest boards, Behance references, design inspiration sources",
      },
      {
        name: "mockupUpload",
        label: "Upload Logo Files & Mockups",
        type: "file",
        helper: "Include logo files, mockups, packaging renders, 3D renders",
      },
      {
        name: "additionalMockups",
        label: "Upload Additional Mockup Images",
        type: "file",
        helper: "Tote bags, packaging, stationery, signage, digital applications",
      },
      {
        name: "finalDeliverables",
        label: "Final Deliverables Checklist",
        type: "textarea",
        placeholder: "List all deliverables: logo files, variations, guidelines, mockups, etc.",
        fullWidth: true,
      },
      {
        name: "projectStatus",
        label: "Project Status",
        type: "text",
        placeholder: "Completed, In Progress, On Hold, Archived",
      },
      {
        name: "tags",
        label: "Tags / Categories",
        type: "textarea",
        placeholder: "Logo design, brand identity, packaging, corporate, startup, etc.",
      },
      {
        name: "featuredImage",
        label: "Featured Image URL (Portfolio)",
        type: "url",
        placeholder: "Hero image for portfolio showcase",
      },
      {
        name: "caseStudyLink",
        label: "Case Study Link",
        type: "url",
        placeholder: "Link to detailed case study or project page",
      },
      {
        name: "clientTestimonial",
        label: "Client Testimonial",
        type: "textarea",
        placeholder: "Client feedback, quote, review",
        fullWidth: true,
      },
      {
        name: "teamMembers",
        label: "Team Members Involved",
        type: "textarea",
        placeholder: "Designer names, roles, contributions",
      },
      {
        name: "projectNotes",
        label: "Additional Project Notes",
        type: "textarea",
        placeholder: "Any additional context, challenges, solutions, process details",
        fullWidth: true,
      },
    ],
    sampleEntries: [
      {
        companyName: "Orbit CRM",
        projectDescription: "Hero orbital logo + 3D merch mockups",
        primaryLogo: "https://cdn.webfudge.com/orbit/logo.png",
        supportingAssets: "Car wraps, carry bag system, stationery kit",
        mockupUpload: "orbit-mockups.zip",
      },
    ],
  },
  {
    key: "brand",
    slug: "brand-identity",
    title: "Brand Identity",
    tagline: "Systems, tone and collateral",
    description:
      "Document the full identity system, brand story and reference links.",
    gradient: "from-emerald-500/60 via-blue-500/50 to-cyan-500/60",
    fields: [
      {
        name: "brandName",
        label: "Brand / Company Name",
        type: "text",
        placeholder: "Nourish Health",
      },
      {
        name: "clientCompany",
        label: "Client Company Information",
        type: "textarea",
        placeholder: "Company name, industry, location, size",
      },
      {
        name: "clientContact",
        label: "Client Contact Information",
        type: "textarea",
        placeholder: "Name, email, phone, role",
      },
      {
        name: "projectYear",
        label: "Project Year",
        type: "text",
        placeholder: "2024",
      },
      {
        name: "projectTimeline",
        label: "Project Timeline",
        type: "textarea",
        placeholder: "Start date, phases, milestones, completion date",
      },
      {
        name: "brandStory",
        label: "Brand Story & Feel",
        type: "textarea",
        placeholder: "Positioning statement, tone, personality cues...",
        fullWidth: true,
      },
      {
        name: "brandPositioning",
        label: "Brand Positioning Statement",
        type: "textarea",
        placeholder: "How the brand positions itself in the market",
        fullWidth: true,
      },
      {
        name: "targetAudience",
        label: "Target Audience",
        type: "textarea",
        placeholder: "Demographics, psychographics, personas, market segments",
        fullWidth: true,
      },
      {
        name: "brandValues",
        label: "Brand Values",
        type: "textarea",
        placeholder: "Core values, principles, beliefs that guide the brand",
      },
      {
        name: "brandPersonality",
        label: "Brand Personality Traits",
        type: "textarea",
        placeholder: "Adjectives that describe the brand (e.g., bold, friendly, innovative, trustworthy)",
      },
      {
        name: "brandVoice",
        label: "Brand Voice & Tone",
        type: "textarea",
        placeholder: "Communication style, tone guidelines, voice characteristics",
        fullWidth: true,
      },
      {
        name: "messagingFramework",
        label: "Messaging Framework",
        type: "textarea",
        placeholder: "Key messages, taglines, value propositions, elevator pitch",
        fullWidth: true,
      },
      {
        name: "colorPalette",
        label: "Color Palette",
        type: "textarea",
        placeholder: "Primary colors, secondary colors, accent colors, hex codes, RGB values, usage guidelines",
        fullWidth: true,
      },
      {
        name: "typographySystem",
        label: "Typography System",
        type: "textarea",
        placeholder: "Headings font, body font, display font, weights, sizes, hierarchy",
        fullWidth: true,
      },
      {
        name: "logoVariations",
        label: "Logo Variations & Applications",
        type: "textarea",
        placeholder: "Primary logo, secondary logo, icon, wordmark, usage examples",
      },
      {
        name: "iconSystem",
        label: "Icon System",
        type: "textarea",
        placeholder: "Icon style, library, usage guidelines, custom icons",
      },
      {
        name: "photographyStyle",
        label: "Photography Style",
        type: "textarea",
        placeholder: "Photo style, mood, composition, color treatment, subject matter",
      },
      {
        name: "illustrationStyle",
        label: "Illustration Style",
        type: "textarea",
        placeholder: "Illustration approach, style guide, examples, usage",
      },
      {
        name: "patternTexture",
        label: "Pattern / Texture Elements",
        type: "textarea",
        placeholder: "Pattern designs, textures, decorative elements, applications",
      },
      {
        name: "website",
        label: "Website / Landing URL",
        type: "url",
        placeholder: "https://nourish.health",
      },
      {
        name: "applicationExamples",
        label: "Application Examples",
        type: "textarea",
        placeholder: "Business cards, letterhead, packaging, signage, digital applications, merchandise",
        fullWidth: true,
      },
      {
        name: "socialMediaTemplates",
        label: "Social Media Templates",
        type: "textarea",
        placeholder: "Post templates, story templates, cover images, profile assets",
      },
      {
        name: "brandAssetsLibrary",
        label: "Brand Assets Library Link",
        type: "url",
        placeholder: "Link to asset library, Dropbox, Google Drive, or brand portal",
      },
      {
        name: "brandGuidelinesPDF",
        label: "Brand Guidelines PDF Link",
        type: "url",
        placeholder: "Link to comprehensive brand guidelines document",
      },
      {
        name: "styleGuideLink",
        label: "Style Guide Link (Interactive)",
        type: "url",
        placeholder: "Link to interactive style guide, Figma, or online platform",
      },
      {
        name: "referenceLinks",
        label: "Reference Links (Notion, decks, etc.)",
        type: "textarea",
        placeholder: "https://notion.so/... • https://figma.com/file/... • https://miro.com/...",
        fullWidth: true,
      },
      {
        name: "inspirationMoodboard",
        label: "Inspiration / Mood Board Links",
        type: "textarea",
        placeholder: "Pinterest, Behance, design references, competitive analysis",
      },
      {
        name: "catalogue",
        label: "Upload Brand Guidelines / Catalogue",
        type: "file",
        helper: "PDF guidelines, catalogues or interactive style guides.",
      },
      {
        name: "brandAssetsUpload",
        label: "Upload Brand Assets",
        type: "file",
        helper: "Logo files, icons, patterns, templates, application examples",
      },
      {
        name: "applicationMockups",
        label: "Upload Application Mockups",
        type: "file",
        helper: "Business cards, packaging, signage, digital mockups, merchandise",
      },
      {
        name: "projectStatus",
        label: "Project Status",
        type: "text",
        placeholder: "Completed, In Progress, On Hold, Archived",
      },
      {
        name: "clientIndustry",
        label: "Client Industry",
        type: "text",
        placeholder: "Healthcare, Technology, Fashion, Food & Beverage, etc.",
      },
      {
        name: "tags",
        label: "Tags / Categories",
        type: "textarea",
        placeholder: "Brand identity, rebrand, startup, corporate, lifestyle, etc.",
      },
      {
        name: "featuredImage",
        label: "Featured Image URL (Portfolio)",
        type: "url",
        placeholder: "Hero image for portfolio showcase",
      },
      {
        name: "caseStudyLink",
        label: "Case Study Link",
        type: "url",
        placeholder: "Link to detailed case study or project page",
      },
      {
        name: "clientTestimonial",
        label: "Client Testimonial",
        type: "textarea",
        placeholder: "Client feedback, quote, review",
        fullWidth: true,
      },
      {
        name: "teamMembers",
        label: "Team Members & Credits",
        type: "textarea",
        placeholder: "Designer names, roles, contributions, creative director, etc.",
      },
      {
        name: "projectNotes",
        label: "Additional Project Notes",
        type: "textarea",
        placeholder: "Process, challenges, solutions, research insights, design decisions",
        fullWidth: true,
      },
    ],
    sampleEntries: [
      {
        brandName: "Nourish Health",
        brandStory: "Gen-Z wellness identity revamp",
        website: "https://nourish.health",
        referenceLinks: "https://notion.so/nourish • https://figma.com/file/...",
        catalogue: "nourish-identity.pdf",
      },
    ],
  },
  {
    key: "graphic",
    slug: "graphic-design",
    title: "Graphic Designing",
    tagline: "Campaigns, posters & layouts",
    description:
      "Curate hero visuals, drop live links (Figma, Canvas) and describe outcomes.",
    gradient: "from-pink-500/60 via-rose-500/60 to-yellow-400/70",
    fields: [
      {
        name: "campaignName",
        label: "Campaign / Project Name",
        type: "text",
        placeholder: "Drip launch visuals",
      },
      {
        name: "clientName",
        label: "Client Name",
        type: "text",
        placeholder: "Client or brand name",
      },
      {
        name: "clientContact",
        label: "Client Contact Information",
        type: "textarea",
        placeholder: "Name, email, phone, role",
      },
      {
        name: "projectYear",
        label: "Project Year",
        type: "text",
        placeholder: "2024",
      },
      {
        name: "projectTimeline",
        label: "Project Timeline / Campaign Duration",
        type: "textarea",
        placeholder: "Start date, phases, launch date, campaign duration",
      },
      {
        name: "campaignObjective",
        label: "Campaign Objective",
        type: "textarea",
        placeholder: "Primary goals, KPIs, target outcomes, success metrics",
        fullWidth: true,
      },
      {
        name: "targetAudience",
        label: "Target Audience",
        type: "textarea",
        placeholder: "Demographics, psychographics, personas, market segments",
        fullWidth: true,
      },
      {
        name: "platformsUsed",
        label: "Platforms / Channels Used",
        type: "textarea",
        placeholder: "Instagram, Facebook, Twitter, LinkedIn, TikTok, Print, OOH, Email, etc.",
      },
      {
        name: "designStyle",
        label: "Design Style / Theme",
        type: "textarea",
        placeholder: "Minimalist, bold, retro, modern, playful, corporate, etc.",
      },
      {
        name: "colorScheme",
        label: "Color Scheme",
        type: "textarea",
        placeholder: "Primary colors, accent colors, hex codes, color psychology",
        fullWidth: true,
      },
      {
        name: "typographyChoices",
        label: "Typography Choices",
        type: "textarea",
        placeholder: "Font families, weights, sizes, hierarchy, custom lettering",
      },
      {
        name: "visualHighlights",
        label: "Visual Highlights",
        type: "textarea",
        placeholder: "Key graphic systems, typography choices, storyboards...",
        fullWidth: true,
      },
      {
        name: "keyVisualElements",
        label: "Key Visual Elements",
        type: "textarea",
        placeholder: "Icons, illustrations, patterns, shapes, imagery style, graphics",
        fullWidth: true,
      },
      {
        name: "designVariations",
        label: "Design Variations",
        type: "textarea",
        placeholder: "Different versions, A/B test variations, seasonal adaptations",
      },
      {
        name: "mockupsApplications",
        label: "Mockups / Applications",
        type: "textarea",
        placeholder: "Social media posts, posters, banners, billboards, packaging, etc.",
        fullWidth: true,
      },
      {
        name: "printSpecifications",
        label: "Print Specifications (if applicable)",
        type: "textarea",
        placeholder: "Dimensions, paper type, finish, printing method, quantities",
      },
      {
        name: "digitalSpecifications",
        label: "Digital Specifications",
        type: "textarea",
        placeholder: "Dimensions, file formats, resolutions, file sizes, optimization",
      },
      {
        name: "animationMotion",
        label: "Animation / Motion Graphics",
        type: "textarea",
        placeholder: "Animated elements, GIFs, video graphics, motion design details",
      },
      {
        name: "interactiveElements",
        label: "Interactive Elements",
        type: "textarea",
        placeholder: "Interactive graphics, web animations, micro-interactions",
      },
      {
        name: "liveLinks",
        label: "Live Links (Figma, Canva, Behance, etc.)",
        type: "textarea",
        placeholder: "Figma, Canva, Behance or live landing pages",
        fullWidth: true,
      },
      {
        name: "portfolioLinks",
        label: "Portfolio / Showcase Links",
        type: "textarea",
        placeholder: "Behance, Dribbble, personal portfolio, case study pages",
      },
      {
        name: "performanceMetrics",
        label: "Performance Metrics / Results",
        type: "textarea",
        placeholder: "Engagement rates, reach, impressions, conversions, ROI, campaign results",
        fullWidth: true,
      },
      {
        name: "clientFeedback",
        label: "Client Feedback",
        type: "textarea",
        placeholder: "Client reactions, feedback, testimonials, approval process",
      },
      {
        name: "inspirationSources",
        label: "Inspiration Sources",
        type: "textarea",
        placeholder: "Design references, mood boards, competitive analysis, trends",
      },
      {
        name: "designProcess",
        label: "Design Process Documentation",
        type: "textarea",
        placeholder: "Research, ideation, iterations, revisions, finalization process",
        fullWidth: true,
      },
      {
        name: "finalDeliverables",
        label: "Final Deliverables",
        type: "textarea",
        placeholder: "List all deliverables: files, formats, variations, guidelines",
        fullWidth: true,
      },
      {
        name: "assetUpload",
        label: "Upload Design Assets / Boards",
        type: "file",
        helper: "PNG/JPG exports or PDF boards.",
      },
      {
        name: "mockupUpload",
        label: "Upload Mockups & Applications",
        type: "file",
        helper: "Mockup images, application examples, final designs",
      },
      {
        name: "sourceFilesUpload",
        label: "Upload Source Files",
        type: "file",
        helper: "AI, PSD, Figma files, editable source files",
      },
      {
        name: "projectStatus",
        label: "Project Status",
        type: "text",
        placeholder: "Completed, In Progress, On Hold, Archived",
      },
      {
        name: "tags",
        label: "Tags / Categories",
        type: "textarea",
        placeholder: "Poster design, social media, print, digital, campaign, etc.",
      },
      {
        name: "featuredWork",
        label: "Featured Work Image URL",
        type: "url",
        placeholder: "Hero image for portfolio showcase",
      },
      {
        name: "caseStudyLink",
        label: "Case Study Link",
        type: "url",
        placeholder: "Link to detailed case study or project page",
      },
      {
        name: "teamMembers",
        label: "Team Members & Credits",
        type: "textarea",
        placeholder: "Designer names, roles, contributions, creative director, etc.",
      },
      {
        name: "projectNotes",
        label: "Additional Project Notes",
        type: "textarea",
        placeholder: "Challenges, solutions, creative decisions, lessons learned",
        fullWidth: true,
      },
    ],
    sampleEntries: [
      {
        campaignName: "Drip Launch",
        visualHighlights: "Neon gradients, kinetic type poster system",
        liveLinks: "https://figma.com/file/drip • https://behance.net/drip",
        assetUpload: "drip-campaign.pdf",
      },
    ],
  },
  {
    key: "social",
    slug: "social-media",
    title: "Social Media Marketing & Mgmt",
    tagline: "Content ops & growth",
    description:
      "Capture the live link, campaign pitch, schedule overview and KPI snapshots.",
    gradient: "from-indigo-500/60 via-purple-500/60 to-fuchsia-500/60",
    fields: [
      {
        name: "brandHandle",
        label: "Brand Handle / Channel",
        type: "text",
        placeholder: "@webfudge.studio",
      },
      {
        name: "clientName",
        label: "Client / Brand Name",
        type: "text",
        placeholder: "Client or brand name",
      },
      {
        name: "clientContact",
        label: "Client Contact Information",
        type: "textarea",
        placeholder: "Name, email, phone, role",
      },
      {
        name: "projectYear",
        label: "Project Year",
        type: "text",
        placeholder: "2024",
      },
      {
        name: "campaignDuration",
        label: "Campaign Duration / Timeline",
        type: "textarea",
        placeholder: "Start date, end date, campaign length, phases",
      },
      {
        name: "platforms",
        label: "Platforms Managed",
        type: "textarea",
        placeholder: "Instagram, Facebook, Twitter/X, LinkedIn, TikTok, YouTube, Pinterest, etc.",
        fullWidth: true,
      },
      {
        name: "campaignPitch",
        label: "Campaign Pitch / Strategy Overview",
        type: "textarea",
        placeholder:
          "30-day authority sprint with reels + carousels + influencer pods...",
        fullWidth: true,
      },
      {
        name: "contentStrategy",
        label: "Content Strategy Overview",
        type: "textarea",
        placeholder: "Content pillars, themes, messaging, storytelling approach, content mix",
        fullWidth: true,
      },
      {
        name: "contentTypes",
        label: "Content Types Created",
        type: "textarea",
        placeholder: "Posts, Stories, Reels, Carousels, Videos, IGTV, Live streams, etc.",
      },
      {
        name: "postingSchedule",
        label: "Posting Schedule / Frequency",
        type: "textarea",
        placeholder: "Daily posts, stories frequency, best times, content calendar structure",
      },
      {
        name: "hashtagStrategy",
        label: "Hashtag Strategy",
        type: "textarea",
        placeholder: "Branded hashtags, trending hashtags, niche hashtags, hashtag research",
      },
      {
        name: "influencerCollaborations",
        label: "Influencer Collaborations",
        type: "textarea",
        placeholder: "Influencer names, partnerships, sponsored content, creator pods",
        fullWidth: true,
      },
      {
        name: "paidAdCampaigns",
        label: "Paid Ad Campaigns",
        type: "textarea",
        placeholder: "Ad campaigns, boosted posts, sponsored content, ad spend, targeting",
      },
      {
        name: "liveLink",
        label: "Live Link (Primary Platform)",
        type: "url",
        placeholder: "https://instagram.com/...",
      },
      {
        name: "allPlatformLinks",
        label: "All Platform Links",
        type: "textarea",
        placeholder: "Instagram, Facebook, Twitter, LinkedIn, TikTok, YouTube links",
        fullWidth: true,
      },
      {
        name: "engagementRate",
        label: "Engagement Rate",
        type: "text",
        placeholder: "Average engagement rate percentage",
      },
      {
        name: "followerGrowth",
        label: "Follower Growth",
        type: "textarea",
        placeholder: "Starting followers, current followers, growth percentage, growth rate",
      },
      {
        name: "reachImpressions",
        label: "Reach / Impressions",
        type: "textarea",
        placeholder: "Total reach, impressions, average reach per post, peak performance",
      },
      {
        name: "clickThroughRate",
        label: "Click-Through Rate (CTR)",
        type: "text",
        placeholder: "Average CTR percentage",
      },
      {
        name: "conversionRate",
        label: "Conversion Rate",
        type: "text",
        placeholder: "Conversion rate percentage",
      },
      {
        name: "leadGeneration",
        label: "Lead Generation",
        type: "textarea",
        placeholder: "Leads generated, qualified leads, lead sources, conversion funnel",
      },
      {
        name: "keyMetrics",
        label: "Key Metrics / Outcomes",
        type: "textarea",
        placeholder: "Engagement +184%, reach 2.1M, 48 qualified leads...",
        fullWidth: true,
      },
      {
        name: "contentCalendarLink",
        label: "Content Calendar Link",
        type: "url",
        placeholder: "Link to content calendar (Notion, Google Sheets, Airtable, etc.)",
      },
      {
        name: "analyticsDashboardLink",
        label: "Analytics Dashboard Link",
        type: "url",
        placeholder: "Link to analytics dashboard or reporting tool",
      },
      {
        name: "competitorAnalysis",
        label: "Competitor Analysis",
        type: "textarea",
        placeholder: "Competitor insights, benchmarking, market positioning",
      },
      {
        name: "targetAudience",
        label: "Target Audience Demographics",
        type: "textarea",
        placeholder: "Age, gender, location, interests, behaviors, psychographics",
        fullWidth: true,
      },
      {
        name: "contentThemes",
        label: "Content Themes / Topics",
        type: "textarea",
        placeholder: "Main content pillars, recurring themes, topic clusters",
        fullWidth: true,
      },
      {
        name: "brandVoice",
        label: "Brand Voice Guidelines",
        type: "textarea",
        placeholder: "Tone, style, messaging guidelines, voice characteristics",
      },
      {
        name: "crisisManagement",
        label: "Crisis Management Protocols",
        type: "textarea",
        placeholder: "Response strategies, escalation procedures, communication guidelines",
      },
      {
        name: "communityManagement",
        label: "Community Management Approach",
        type: "textarea",
        placeholder: "Response time, engagement style, moderation, community building",
      },
      {
        name: "toolsUsed",
        label: "Tools Used",
        type: "textarea",
        placeholder: "Scheduling tools (Hootsuite, Buffer), analytics (Sprout Social), design (Canva), etc.",
      },
      {
        name: "teamMembers",
        label: "Team Members",
        type: "textarea",
        placeholder: "Social media manager, content creator, designer, strategist, etc.",
      },
      {
        name: "reportingFrequency",
        label: "Client Reporting Frequency",
        type: "text",
        placeholder: "Weekly, bi-weekly, monthly reports",
      },
      {
        name: "budgetAllocation",
        label: "Budget Allocation",
        type: "textarea",
        placeholder: "Content creation budget, ad spend, influencer budget, tools budget",
      },
      {
        name: "roiMetrics",
        label: "ROI Metrics",
        type: "textarea",
        placeholder: "Return on investment, cost per acquisition, revenue generated, ROI percentage",
        fullWidth: true,
      },
      {
        name: "testimonials",
        label: "Testimonials / Reviews",
        type: "textarea",
        placeholder: "Client testimonials, user reviews, feedback",
        fullWidth: true,
      },
      {
        name: "caseStudyLink",
        label: "Case Study Link",
        type: "url",
        placeholder: "Link to detailed case study or project page",
      },
      {
        name: "projectStatus",
        label: "Project Status",
        type: "text",
        placeholder: "Active, Completed, On Hold, Archived",
      },
      {
        name: "tags",
        label: "Tags / Categories",
        type: "textarea",
        placeholder: "Social media management, content creation, influencer marketing, etc.",
      },
      {
        name: "projectNotes",
        label: "Additional Project Notes",
        type: "textarea",
        placeholder: "Challenges, solutions, strategies, lessons learned, future plans",
        fullWidth: true,
      },
    ],
    sampleEntries: [
      {
        brandHandle: "@orbital.app",
        campaignPitch: "Creator pod takeover with weekly live rooms",
        liveLink: "https://instagram.com/orbital.app",
        keyMetrics: "Reach 2.1M, +184% engagement, 48 SQLs",
      },
    ],
  },
  {
    key: "web",
    slug: "website-development",
    title: "Website Development",
    tagline: "Live builds & product stories",
    description:
      "Log the live URL, company context, stack and add a hero screenshot.",
    gradient: "from-blue-500/70 via-sky-500/60 to-green-400/60",
    fields: [
      {
        name: "siteName",
        label: "Website / Product Name",
        type: "text",
        placeholder: "Pluto Wallet 3.0",
      },
      {
        name: "clientCompany",
        label: "Client Company",
        type: "text",
        placeholder: "Client or company name",
      },
      {
        name: "clientContact",
        label: "Client Contact Information",
        type: "textarea",
        placeholder: "Name, email, phone, role",
      },
      {
        name: "projectYear",
        label: "Project Year",
        type: "text",
        placeholder: "2024",
      },
      {
        name: "projectTimeline",
        label: "Project Timeline",
        type: "textarea",
        placeholder: "Start date, phases, milestones, launch date, completion",
      },
      {
        name: "projectType",
        label: "Project Type",
        type: "textarea",
        placeholder: "Landing Page, E-commerce, SaaS, Portfolio, Blog, Corporate, Web App, etc.",
      },
      {
        name: "liveUrl",
        label: "Live URL",
        type: "url",
        placeholder: "https://pluto.example.com",
      },
      {
        name: "stagingUrl",
        label: "Staging / Development URL",
        type: "url",
        placeholder: "https://staging.pluto.example.com",
      },
      {
        name: "siteDescription",
        label: "Description",
        type: "textarea",
        placeholder:
          "Full-stack marketing site with gated resources and CMS-driven blog...",
        fullWidth: true,
      },
      {
        name: "keyFeatures",
        label: "Key Features List",
        type: "textarea",
        placeholder: "User authentication, payment processing, blog CMS, dashboard, etc.",
        fullWidth: true,
      },
      {
        name: "technologyStack",
        label: "Technology Stack",
        type: "textarea",
        placeholder: "Frontend: React, Next.js | Backend: Node.js, Express | Database: PostgreSQL",
        fullWidth: true,
      },
      {
        name: "frontendStack",
        label: "Frontend Stack",
        type: "textarea",
        placeholder: "React, Next.js, TypeScript, Tailwind CSS, etc.",
      },
      {
        name: "backendStack",
        label: "Backend Stack",
        type: "textarea",
        placeholder: "Node.js, Express, Python, Django, etc.",
      },
      {
        name: "database",
        label: "Database",
        type: "text",
        placeholder: "PostgreSQL, MongoDB, MySQL, etc.",
      },
      {
        name: "cmsUsed",
        label: "CMS Used",
        type: "textarea",
        placeholder: "Sanity, Contentful, Strapi, WordPress, custom CMS, etc.",
      },
      {
        name: "thirdPartyIntegrations",
        label: "Third-party Integrations",
        type: "textarea",
        placeholder: "Stripe, SendGrid, Analytics, Auth0, etc.",
        fullWidth: true,
      },
      {
        name: "paymentGateway",
        label: "Payment Gateway (if applicable)",
        type: "textarea",
        placeholder: "Stripe, PayPal, Square, payment processing details",
      },
      {
        name: "mobileResponsiveness",
        label: "Mobile Responsiveness",
        type: "textarea",
        placeholder: "Responsive design, mobile-first, breakpoints, testing devices",
      },
      {
        name: "browserCompatibility",
        label: "Browser Compatibility",
        type: "textarea",
        placeholder: "Chrome, Firefox, Safari, Edge, supported versions",
      },
      {
        name: "performanceMetrics",
        label: "Performance Metrics",
        type: "textarea",
        placeholder: "Load time, Lighthouse score, Core Web Vitals, optimization details",
        fullWidth: true,
      },
      {
        name: "seoImplementation",
        label: "SEO Implementation",
        type: "textarea",
        placeholder: "Meta tags, structured data, sitemap, robots.txt, SEO strategy",
      },
      {
        name: "accessibilityFeatures",
        label: "Accessibility Features",
        type: "textarea",
        placeholder: "WCAG compliance, ARIA labels, keyboard navigation, screen reader support",
      },
      {
        name: "securityFeatures",
        label: "Security Features",
        type: "textarea",
        placeholder: "SSL, HTTPS, data encryption, security headers, authentication, authorization",
      },
      {
        name: "analyticsSetup",
        label: "Analytics Setup",
        type: "textarea",
        placeholder: "Google Analytics, Mixpanel, custom analytics, tracking implementation",
      },
      {
        name: "userAuthentication",
        label: "User Authentication System",
        type: "textarea",
        placeholder: "Login, registration, password reset, OAuth, social login, 2FA",
      },
      {
        name: "adminPanelFeatures",
        label: "Admin Panel Features",
        type: "textarea",
        placeholder: "Dashboard, content management, user management, analytics, settings",
      },
      {
        name: "apiIntegrations",
        label: "API Integrations",
        type: "textarea",
        placeholder: "REST APIs, GraphQL, webhooks, external services, API documentation",
      },
      {
        name: "databaseStructure",
        label: "Database Structure",
        type: "textarea",
        placeholder: "Schema overview, key tables, relationships, data models",
      },
      {
        name: "deploymentPlatform",
        label: "Deployment Platform",
        type: "text",
        placeholder: "Vercel, Netlify, AWS, Heroku, DigitalOcean, etc.",
      },
      {
        name: "domainHosting",
        label: "Domain & Hosting Info",
        type: "textarea",
        placeholder: "Domain name, hosting provider, DNS configuration",
      },
      {
        name: "sslCertificate",
        label: "SSL Certificate",
        type: "text",
        placeholder: "SSL provider, certificate type, renewal date",
      },
      {
        name: "backupStrategy",
        label: "Backup Strategy",
        type: "textarea",
        placeholder: "Backup frequency, storage location, recovery procedures",
      },
      {
        name: "maintenancePlan",
        label: "Maintenance Plan",
        type: "textarea",
        placeholder: "Update schedule, monitoring, support plan, maintenance tasks",
      },
      {
        name: "stackNotes",
        label: "Stack / Technical Notes",
        type: "textarea",
        placeholder: "Next.js + Sanity + Vercel, edge caching, multiplan pricing...",
        fullWidth: true,
      },
      {
        name: "userFlowDocumentation",
        label: "User Flow Documentation",
        type: "textarea",
        placeholder: "User journeys, flow diagrams, interaction patterns",
      },
      {
        name: "designSystemLink",
        label: "Design System Link",
        type: "url",
        placeholder: "Link to design system, Figma, Storybook, etc.",
      },
      {
        name: "githubRepository",
        label: "GitHub Repository",
        type: "url",
        placeholder: "Link to GitHub repository (if public or shared)",
      },
      {
        name: "documentationLink",
        label: "Documentation Link",
        type: "url",
        placeholder: "Link to project documentation, README, technical docs",
      },
      {
        name: "clientTrainingMaterials",
        label: "Client Training Materials",
        type: "textarea",
        placeholder: "Training docs, video tutorials, user guides, admin guides",
      },
      {
        name: "postLaunchSupport",
        label: "Post-Launch Support",
        type: "textarea",
        placeholder: "Support plan, bug fixes, feature updates, ongoing maintenance",
      },
      {
        name: "conversionMetrics",
        label: "Conversion Metrics",
        type: "textarea",
        placeholder: "Conversion rates, goal completions, user actions, business metrics",
        fullWidth: true,
      },
      {
        name: "userFeedback",
        label: "User Feedback",
        type: "textarea",
        placeholder: "User testimonials, reviews, feedback, usability testing results",
      },
      {
        name: "screenshotUpload",
        label: "Upload Screenshot / Gallery",
        type: "file",
        helper: "Drop hero fold or flow screenshots.",
      },
      {
        name: "additionalScreenshots",
        label: "Upload Additional Screenshots",
        type: "file",
        helper: "More screenshots showing different pages, features, flows",
      },
      {
        name: "videoDemoLink",
        label: "Video Demo Link",
        type: "url",
        placeholder: "Link to video walkthrough or demo",
      },
      {
        name: "caseStudyLink",
        label: "Case Study Link",
        type: "url",
        placeholder: "Link to detailed case study or project page",
      },
      {
        name: "projectStatus",
        label: "Project Status",
        type: "text",
        placeholder: "Live, In Development, On Hold, Archived",
      },
      {
        name: "tags",
        label: "Tags / Categories",
        type: "textarea",
        placeholder: "Web development, SaaS, e-commerce, portfolio, etc.",
      },
      {
        name: "teamMembers",
        label: "Team Members & Credits",
        type: "textarea",
        placeholder: "Developer names, roles, contributions, project manager, designer, etc.",
      },
      {
        name: "projectNotes",
        label: "Additional Project Notes",
        type: "textarea",
        placeholder: "Challenges, solutions, technical decisions, lessons learned, future plans",
        fullWidth: true,
      },
    ],
    sampleEntries: [
      {
        siteName: "Pluto Wallet 3.0",
        liveUrl: "https://pluto.example.com",
        siteDescription: "Product-led growth site revamp",
        stackNotes: "Next.js, Vercel, Sanity CMS",
        screenshotUpload: "pluto-home.png",
      },
    ],
  },
  {
    key: "video",
    slug: "video-editing",
    title: "Video Editing",
    tagline: "Cuts, reels & narratives",
    description:
      "Share the video link, edit breakdown and supporting briefs or assets.",
    gradient: "from-slate-500/60 via-purple-600/60 to-amber-500/60",
    fields: [
      {
        name: "videoTitle",
        label: "Video Title",
        type: "text",
        placeholder: "Astra Launch Film",
      },
      {
        name: "clientProjectName",
        label: "Client / Project Name",
        type: "text",
        placeholder: "Client or project name",
      },
      {
        name: "clientContact",
        label: "Client Contact Information",
        type: "textarea",
        placeholder: "Name, email, phone, role",
      },
      {
        name: "projectYear",
        label: "Project Year",
        type: "text",
        placeholder: "2024",
      },
      {
        name: "projectTimeline",
        label: "Project Timeline",
        type: "textarea",
        placeholder: "Start date, phases, milestones, delivery date, completion",
      },
      {
        name: "videoType",
        label: "Video Type",
        type: "textarea",
        placeholder: "Commercial, Explainer, Social Media, Documentary, Corporate, Product Launch, Event, etc.",
      },
      {
        name: "videoDuration",
        label: "Video Duration",
        type: "text",
        placeholder: "30 seconds, 2 minutes, 5 minutes, etc.",
      },
      {
        name: "aspectRatio",
        label: "Aspect Ratio",
        type: "text",
        placeholder: "16:9, 9:16, 1:1, 4:5, etc.",
      },
      {
        name: "resolution",
        label: "Resolution",
        type: "text",
        placeholder: "1080p, 4K, 8K, etc.",
      },
      {
        name: "frameRate",
        label: "Frame Rate",
        type: "text",
        placeholder: "24fps, 30fps, 60fps, etc.",
      },
      {
        name: "videoLink",
        label: "Video Link (Primary)",
        type: "url",
        placeholder: "https://vimeo.com/...",
      },
      {
        name: "additionalVideoLinks",
        label: "Additional Video Links",
        type: "textarea",
        placeholder: "YouTube, Vimeo, Instagram, TikTok, other platform links",
      },
      {
        name: "colorGradingStyle",
        label: "Color Grading Style",
        type: "textarea",
        placeholder: "Color treatment, mood, LUTs used, color correction approach",
      },
      {
        name: "musicSoundtrack",
        label: "Music / Soundtrack",
        type: "textarea",
        placeholder: "Music track, composer, licensing, sound design elements",
      },
      {
        name: "voiceover",
        label: "Voiceover (if applicable)",
        type: "textarea",
        placeholder: "Voiceover artist, script, language, recording details",
      },
      {
        name: "subtitlesCaptions",
        label: "Subtitles / Captions",
        type: "textarea",
        placeholder: "Languages, style, placement, accessibility features",
      },
      {
        name: "motionGraphics",
        label: "Motion Graphics / Animation",
        type: "textarea",
        placeholder: "Animated elements, graphics, text animations, visual effects",
      },
      {
        name: "visualEffects",
        label: "Visual Effects (VFX)",
        type: "textarea",
        placeholder: "VFX elements, compositing, special effects, post-production",
      },
      {
        name: "editingSoftware",
        label: "Editing Software Used",
        type: "textarea",
        placeholder: "Premiere Pro, Final Cut Pro, DaVinci Resolve, After Effects, etc.",
      },
      {
        name: "rawFootageSource",
        label: "Raw Footage Source",
        type: "textarea",
        placeholder: "Footage sources, camera types, shooting locations, production details",
      },
      {
        name: "scriptStoryboard",
        label: "Script / Storyboard",
        type: "textarea",
        placeholder: "Script details, storyboard references, narrative structure",
      },
      {
        name: "editNotes",
        label: "Edit Notes / Narrative",
        type: "textarea",
        placeholder:
          "Structure, pacing, motion cues, grade references, sound design...",
        fullWidth: true,
      },
      {
        name: "editingStyle",
        label: "Editing Style / Approach",
        type: "textarea",
        placeholder: "Fast-paced, cinematic, documentary style, jump cuts, transitions",
      },
      {
        name: "clientFeedbackRounds",
        label: "Client Feedback Rounds",
        type: "textarea",
        placeholder: "Number of revisions, feedback process, approval stages",
      },
      {
        name: "revisionCount",
        label: "Revision Count",
        type: "text",
        placeholder: "Number of revisions completed",
      },
      {
        name: "deliverables",
        label: "Deliverables",
        type: "textarea",
        placeholder: "Hero film, vertical cut, teaser loops, thumb kit...",
        fullWidth: true,
      },
      {
        name: "deliverableFormats",
        label: "Deliverable Formats",
        type: "textarea",
        placeholder: "MP4, MOV, ProRes, H.264, file sizes, compression settings",
      },
      {
        name: "distributionPlatforms",
        label: "Distribution Platforms",
        type: "textarea",
        placeholder: "YouTube, Vimeo, Instagram, TikTok, website, TV, etc.",
      },
      {
        name: "performanceMetrics",
        label: "Performance Metrics",
        type: "textarea",
        placeholder: "Views, engagement, watch time, shares, conversions, ROI",
        fullWidth: true,
      },
      {
        name: "clientTestimonial",
        label: "Client Testimonial",
        type: "textarea",
        placeholder: "Client feedback, quote, review",
        fullWidth: true,
      },
      {
        name: "behindScenes",
        label: "Behind-the-Scenes Content",
        type: "textarea",
        placeholder: "BTS photos, videos, process documentation, making-of content",
      },
      {
        name: "teamCredits",
        label: "Team Credits",
        type: "textarea",
        placeholder: "Editor, director, producer, colorist, sound designer, etc.",
      },
      {
        name: "equipmentUsed",
        label: "Equipment Used",
        type: "textarea",
        placeholder: "Cameras, lenses, lighting, audio equipment, editing hardware",
      },
      {
        name: "locationSetting",
        label: "Location / Setting",
        type: "textarea",
        placeholder: "Shooting locations, studio, on-location, virtual sets",
      },
      {
        name: "talentCast",
        label: "Talent / Cast",
        type: "textarea",
        placeholder: "Actors, presenters, models, talent involved",
      },
      {
        name: "productionCompany",
        label: "Production Company",
        type: "text",
        placeholder: "Production company name (if applicable)",
      },
      {
        name: "briefUpload",
        label: "Upload Brief / Assets",
        type: "file",
        helper: "Attach scripts, storyboard PDFs or LUT packages.",
      },
      {
        name: "rawFootageUpload",
        label: "Upload Raw Footage Samples",
        type: "file",
        helper: "Sample raw footage clips (if applicable)",
      },
      {
        name: "finalVideoUpload",
        label: "Upload Final Video Files",
        type: "file",
        helper: "Final video files, different formats, variations",
      },
      {
        name: "portfolioLink",
        label: "Portfolio Link",
        type: "url",
        placeholder: "Link to portfolio showcase or case study",
      },
      {
        name: "caseStudyLink",
        label: "Case Study Link",
        type: "url",
        placeholder: "Link to detailed case study or project page",
      },
      {
        name: "projectStatus",
        label: "Project Status",
        type: "text",
        placeholder: "Completed, In Progress, On Hold, Archived",
      },
      {
        name: "tags",
        label: "Tags / Categories",
        type: "textarea",
        placeholder: "Video editing, commercial, social media, corporate, etc.",
      },
      {
        name: "projectNotes",
        label: "Additional Project Notes",
        type: "textarea",
        placeholder: "Challenges, solutions, creative decisions, technical notes, lessons learned",
        fullWidth: true,
      },
    ],
    sampleEntries: [
      {
        videoTitle: "Astra Launch Film",
        videoLink: "https://vimeo.com/astra",
        editNotes: "High-energy cut with product macro shots",
        deliverables: "Hero film, teaser loops, thumb kit",
        briefUpload: "astra-brief.pdf",
      },
    ],
  },
];

export const projectSectionsBySlug = projectSections.reduce<Record<string, SectionConfig>>(
  (acc, section) => {
    acc[section.slug] = section;
    return acc;
  },
  {},
);

